apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: test-ingress
spec:
  tls:
  - hosts:
    - web.example.com
    secretName: ciscolive-secret
  rules:
   - host: web.example.com
     http:
       paths:
         - path: /welcome/
           backend:
             serviceName: ciscolivewelcomeweb
             servicePort: 80
         - path: /thanks/
           backend:
             serviceName: ciscolivethanksweb
             servicePort: 80

